"""
memory.py — Workstream 1: Agentic Semantic Memory Layer
========================================================
Transforms the ontology graph store from a static semantic schema into
the long-term working memory of AI agents.  Every reasoning chain,
observation, and decision becomes a queryable, temporally-ordered fact.

Three primary operations:
    memory.recall(query, flavor, time_range)
        SPARQL query over ObservationRecord graph, filtered by time window
        and ontology class.  Returns typed JSON-LD objects.

    memory.diff(agent_a, agent_b, subject)
        Returns assertions where two agent flavors disagreed on the same
        subject within the ObservationRecord store.

    memory.consolidate(older_than_days)
        Marks superseded observations as prov:wasInvalidatedBy, reducing
        graph size.  Returns a consolidation summary dict.

All operations return typed JSON-LD objects ready for payload injection.

Usage:
    from runtime.memory import AgentMemory
    mem = AgentMemory(db_path="db/enterprise.db")
    results = mem.recall("degraded network functions", flavor="network-ops")
    diff    = mem.diff("network-ops", "fault-management", subject="AMF-East-01")
    summary = mem.consolidate(older_than_days=90)
"""

import json
import os
import sqlite3
import uuid
from datetime import datetime, timedelta, timezone
from typing import Any, Dict, List, Optional, Tuple


# ─── IRI prefix used throughout this module ──────────────────────────────────

_BASE_IRI = "https://ontology.example.com/tmf/"
_PROV      = "http://www.w3.org/ns/prov#"
_OWL       = "http://www.w3.org/2002/07/owl#"
_XSD       = "http://www.w3.org/2001/XMLSchema#"


# ─── JSON-LD context emitted by all memory operations ────────────────────────

_MEMORY_CONTEXT: Dict[str, Any] = {
    "@context": {
        "@vocab":       _BASE_IRI,
        "prov":         _PROV,
        "owl":          _OWL,
        "xsd":          _XSD,
        "rdfs":         "http://www.w3.org/2000/01/rdf-schema#",
        "generatedAt":  {"@id": "prov:generatedAtTime", "@type": "xsd:dateTime"},
        "invalidatedBy":{"@id": "prov:wasInvalidatedBy", "@type": "@id"},
        "influencedBy": {"@id": "prov:wasInfluencedBy",  "@type": "@id"},
        "attributedTo": {"@id": "prov:wasAttributedTo",  "@type": "@id"},
        "versionInfo":  {"@id": "owl:versionInfo"},
    }
}


# ─── Helpers ─────────────────────────────────────────────────────────────────

def _utcnow() -> str:
    return datetime.now(timezone.utc).isoformat()


def _days_ago(n: int) -> str:
    return (datetime.now(timezone.utc) - timedelta(days=n)).isoformat()


def _connect(db_path: str) -> sqlite3.Connection:
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    return conn


# ─── Main class ──────────────────────────────────────────────────────────────

class AgentMemory:
    """Long-term semantic memory interface for AI agents.

    Provides recall, diff, and consolidate operations over the
    ObservationRecord graph store.  All results are typed JSON-LD objects
    ready for direct injection into LLM payloads.

    Args:
        db_path: Absolute path to the SQLite enterprise database.
        temporal_queries_dir: Optional path to the directory containing
            parameterised SPARQL templates.  Defaults to
            ``runtime/temporal_queries/`` relative to this file.
    """

    def __init__(
        self,
        db_path: str,
        temporal_queries_dir: Optional[str] = None,
    ) -> None:
        self._db_path = db_path
        _here = os.path.dirname(os.path.abspath(__file__))
        self._tq_dir = temporal_queries_dir or os.path.join(
            _here, "temporal_queries"
        )

    # ─────────────────────────────────────────────────────────────────────
    # Public API
    # ─────────────────────────────────────────────────────────────────────

    def recall(
        self,
        query: str,
        flavor: Optional[str] = None,
        time_range: Optional[Tuple[str, str]] = None,
        record_type: Optional[str] = None,
        limit: int = 50,
    ) -> Dict[str, Any]:
        """Retrieve prior reasoning observations matching a query.

        Searches the ObservationRecord store using keyword matching and
        optional temporal / flavor / type filters.  Results are ordered
        by recency (most recent first).

        Args:
            query: Free-text search string matched against the stored
                   LLM response text and source_ref.
            flavor: Restrict results to observations generated by this
                    agent flavor.  ``None`` returns all flavors.
            time_range: Optional ``(iso_from, iso_to)`` tuple.  Both ends
                        are inclusive.  ``None`` returns all time.
            record_type: Optional record_type filter, e.g. ``"RESPONSE"``,
                         ``"MEASURED"``, ``"INFERRED"``.
            limit: Maximum number of records to return (default 50).

        Returns:
            A typed JSON-LD dict::

                {
                  "@context": {...},
                  "@type": "MemoryRecallResult",
                  "@id": "https://…/memory/recall/<uuid>",
                  "query": "...",
                  "flavor": "...",
                  "time_range": {"from": "...", "to": "..."},
                  "result_count": N,
                  "generated_at": "...",
                  "@graph": [<ObservationRecord>, ...]
                }
        """
        rows = self._query_observations(
            query=query,
            flavor=flavor,
            time_range=time_range,
            record_type=record_type,
            limit=limit,
        )

        graph = [self._row_to_jsonld(r) for r in rows]

        tf, tt = ("*", "*")
        if time_range:
            tf, tt = time_range[0], time_range[1]

        return {
            **_MEMORY_CONTEXT,
            "@type":        "MemoryRecallResult",
            "@id":          f"{_BASE_IRI}memory/recall/{uuid.uuid4()}",
            "query":         query,
            "flavor":        flavor,
            "time_range":    {"from": tf, "to": tt},
            "result_count":  len(graph),
            "generatedAt":   _utcnow(),
            "@graph":        graph,
        }

    def diff(
        self,
        agent_a: str,
        agent_b: str,
        subject: Optional[str] = None,
        limit: int = 100,
    ) -> Dict[str, Any]:
        """Identify assertions where two agent flavors disagreed.

        Compares ObservationRecord entries from *agent_a* and *agent_b*
        that share the same ``entity_iri`` (and optional ``subject`` filter)
        but carry different ``value_text`` content, indicating a
        disagreement on the same observed entity.

        Implements ``prov:wasInfluencedBy`` links between conflicting pairs
        so downstream agents can trace the disagreement.

        Args:
            agent_a: First agent flavor name (e.g. ``"network-ops"``).
            agent_b: Second agent flavor name (e.g. ``"fault-management"``).
            subject: Optional entity IRI or substring to restrict the diff.
            limit: Maximum number of disagreement pairs to return.

        Returns:
            A typed JSON-LD dict::

                {
                  "@context": {...},
                  "@type": "MemoryDiffResult",
                  "agent_a": "...", "agent_b": "...",
                  "disagreement_count": N,
                  "@graph": [<DisagreementPair>, ...]
                }
        """
        pairs = self._find_disagreements(agent_a, agent_b, subject, limit)

        graph = []
        for row_a, row_b in pairs:
            pair_id = f"{_BASE_IRI}memory/diff/{uuid.uuid4()}"
            graph.append({
                "@type":          "DisagreementPair",
                "@id":             pair_id,
                "entity_iri":      row_a["entity_iri"],
                "agent_a_record":  self._row_to_jsonld(row_a),
                "agent_b_record":  self._row_to_jsonld(row_b),
                "influencedBy":    row_b["record_iri"],
                "generatedAt":     _utcnow(),
            })

        return {
            **_MEMORY_CONTEXT,
            "@type":               "MemoryDiffResult",
            "@id":                 f"{_BASE_IRI}memory/diff/result/{uuid.uuid4()}",
            "agent_a":              agent_a,
            "agent_b":              agent_b,
            "subject_filter":       subject,
            "disagreement_count":   len(graph),
            "generatedAt":          _utcnow(),
            "@graph":               graph,
        }

    def consolidate(
        self,
        older_than_days: int = 90,
        dry_run: bool = False,
    ) -> Dict[str, Any]:
        """Run memory consolidation across three strategies.

        **Strategy 1 — Supersession:** When a MEASURED observation replaces
        an INFERRED one for the same entity, mark the INFERRED record with
        ``prov:wasInvalidatedBy`` pointing to the MEASURED record IRI.

        **Strategy 2 — Temporal compression:** Aggregate MEASURED point
        observations older than ``older_than_days`` into a single summary
        record per entity and record type, reducing graph size.

        **Strategy 3 — Conflict escalation:** When two MEASURED observations
        on the same entity disagree, and neither has been invalidated, create
        a ``ConflictEvent`` record for human review.

        Args:
            older_than_days: Age threshold in calendar days for supersession
                and compression strategies (default 90).
            dry_run: If ``True``, compute what *would* be done but make no
                     DB changes.

        Returns:
            A consolidation summary dict::

                {
                  "@type": "ConsolidationSummary",
                  "superseded_count": N,
                  "compressed_count": N,
                  "conflicts_raised": N,
                  "graph_size_before": N,
                  "graph_size_after": N,
                  "reduction_pct": N,
                  "dry_run": bool,
                  "generatedAt": "..."
                }
        """
        cutoff = _days_ago(older_than_days)

        size_before = self._graph_size()

        superseded   = self._supersede_inferred(cutoff, dry_run)
        compressed   = self._compress_old_observations(cutoff, dry_run)
        conflicts    = self._escalate_conflicts(dry_run)

        size_after = self._graph_size()

        reduction = 0.0
        if size_before > 0:
            reduction = round((size_before - size_after) / size_before * 100, 1)

        return {
            **_MEMORY_CONTEXT,
            "@type":              "ConsolidationSummary",
            "@id":                f"{_BASE_IRI}memory/consolidation/{uuid.uuid4()}",
            "superseded_count":    superseded,
            "compressed_count":    compressed,
            "conflicts_raised":    conflicts,
            "graph_size_before":   size_before,
            "graph_size_after":    size_after,
            "reduction_pct":       reduction,
            "older_than_days":     older_than_days,
            "dry_run":             dry_run,
            "generatedAt":         _utcnow(),
        }

    # ─────────────────────────────────────────────────────────────────────
    # Temporal point-in-time snapshot
    # ─────────────────────────────────────────────────────────────────────

    def snapshot(
        self,
        at: str,
        entity_iri: Optional[str] = None,
        flavor: Optional[str] = None,
    ) -> Dict[str, Any]:
        """Return the ontology state as observed at a specific timestamp.

        Finds all non-invalidated observations valid *at* the given ISO
        timestamp, providing a point-in-time view of what agents knew.

        Args:
            at: ISO 8601 timestamp (e.g. ``"2026-04-10T02:00:00+00:00"``).
            entity_iri: Optional entity IRI to restrict the snapshot.
            flavor: Optional flavor scope filter.

        Returns:
            A typed JSON-LD dict with ``@graph`` of valid observations at *at*.
        """
        rows = self._snapshot_at(at, entity_iri, flavor)
        graph = [self._row_to_jsonld(r) for r in rows]

        return {
            **_MEMORY_CONTEXT,
            "@type":         "TemporalSnapshot",
            "@id":           f"{_BASE_IRI}memory/snapshot/{uuid.uuid4()}",
            "snapshotAt":    at,
            "entity_filter": entity_iri,
            "flavor":        flavor,
            "record_count":  len(graph),
            "generatedAt":   _utcnow(),
            "@graph":        graph,
        }

    # ─────────────────────────────────────────────────────────────────────
    # Agent influence graph
    # ─────────────────────────────────────────────────────────────────────

    def influence_graph(
        self,
        agent: Optional[str] = None,
        limit: int = 200,
    ) -> Dict[str, Any]:
        """Return the agent-to-agent influence graph via PROV-O links.

        Retrieves ``prov:wasInfluencedBy`` edges stored during cross-agent
        diff operations, surfacing which agents are building on whose prior
        reasoning and where circular dependencies exist.

        Args:
            agent: Filter to edges involving this agent flavor (as source or
                   target).  ``None`` returns the full graph.
            limit: Maximum edges to return.

        Returns:
            A typed JSON-LD dict with ``@graph`` of influence edge nodes.
        """
        edges = self._get_influence_edges(agent, limit)

        return {
            **_MEMORY_CONTEXT,
            "@type":       "AgentInfluenceGraph",
            "@id":         f"{_BASE_IRI}memory/influence/{uuid.uuid4()}",
            "agent_filter": agent,
            "edge_count":   len(edges),
            "generatedAt":  _utcnow(),
            "@graph":       edges,
        }

    # ─────────────────────────────────────────────────────────────────────
    # Private — DB query helpers
    # ─────────────────────────────────────────────────────────────────────

    def _query_observations(
        self,
        query: str,
        flavor: Optional[str],
        time_range: Optional[Tuple[str, str]],
        record_type: Optional[str],
        limit: int,
    ) -> List[sqlite3.Row]:
        """Fetch ObservationRecord rows matching filter criteria."""
        sql_parts = [
            """
            SELECT * FROM observation_record
            WHERE (value_text LIKE ? OR source_ref LIKE ?)
              AND (invalidated_by IS NULL OR invalidated_by = '')
            """
        ]
        params: List[Any] = [f"%{query}%", f"%{query}%"]

        if flavor:
            sql_parts.append(
                "AND entity_iri LIKE ?"
            )
            params.append(f"%/flavor/{flavor}%")

        if time_range:
            sql_parts.append("AND generated_at >= ? AND generated_at <= ?")
            params.extend([time_range[0], time_range[1]])

        if record_type:
            sql_parts.append("AND record_type = ?")
            params.append(record_type)

        sql_parts.append("ORDER BY generated_at DESC LIMIT ?")
        params.append(limit)

        sql = " ".join(sql_parts)

        try:
            conn = _connect(self._db_path)
            rows = conn.execute(sql, params).fetchall()
            conn.close()
            return rows
        except Exception as exc:
            print(f"  WARN AgentMemory.recall: {exc}")
            return []

    def _find_disagreements(
        self,
        agent_a: str,
        agent_b: str,
        subject: Optional[str],
        limit: int,
    ) -> List[Tuple[sqlite3.Row, sqlite3.Row]]:
        """Find observation pairs where two agent flavors disagree."""
        base_sql = """
            SELECT * FROM observation_record
            WHERE entity_iri LIKE ?
              AND (invalidated_by IS NULL OR invalidated_by = '')
        """
        subject_filter = f"%{subject}%" if subject else "%"
        params_base: List[Any] = [subject_filter]

        try:
            conn = _connect(self._db_path)

            rows_a = conn.execute(
                base_sql + " AND source_ref LIKE ?",
                params_base + [f"%{agent_a}%"],
            ).fetchall()

            rows_b_index: Dict[str, sqlite3.Row] = {}
            rows_b_all = conn.execute(
                base_sql + " AND source_ref LIKE ?",
                params_base + [f"%{agent_b}%"],
            ).fetchall()
            for r in rows_b_all:
                iri = r["entity_iri"]
                # Keep only the most recent per entity
                if iri not in rows_b_index or r["generated_at"] > rows_b_index[iri]["generated_at"]:
                    rows_b_index[iri] = r

            conn.close()

            pairs: List[Tuple[sqlite3.Row, sqlite3.Row]] = []
            for row_a in rows_a:
                iri = row_a["entity_iri"]
                if iri in rows_b_index:
                    row_b = rows_b_index[iri]
                    # Only include genuine disagreements (different text content)
                    if (row_a["value_text"] or "") != (row_b["value_text"] or ""):
                        pairs.append((row_a, row_b))
                if len(pairs) >= limit:
                    break

            return pairs

        except Exception as exc:
            print(f"  WARN AgentMemory.diff: {exc}")
            return []

    def _snapshot_at(
        self,
        at: str,
        entity_iri: Optional[str],
        flavor: Optional[str],
    ) -> List[sqlite3.Row]:
        """Retrieve non-invalidated observations valid at timestamp *at*."""
        sql = """
            SELECT * FROM observation_record
            WHERE generated_at <= ?
              AND (valid_from IS NULL OR valid_from <= ?)
              AND (invalidated_by IS NULL OR invalidated_by = '')
        """
        params: List[Any] = [at, at]

        if entity_iri:
            sql += " AND entity_iri LIKE ?"
            params.append(f"%{entity_iri}%")

        if flavor:
            sql += " AND source_ref LIKE ?"
            params.append(f"%{flavor}%")

        sql += " ORDER BY generated_at DESC"

        try:
            conn = _connect(self._db_path)
            rows = conn.execute(sql, params).fetchall()
            conn.close()
            return rows
        except Exception as exc:
            print(f"  WARN AgentMemory.snapshot: {exc}")
            return []

    def _get_influence_edges(
        self, agent: Optional[str], limit: int
    ) -> List[Dict[str, Any]]:
        """Retrieve influence-graph edges from the influence_log table."""
        sql = "SELECT * FROM memory_influence_log"
        params: List[Any] = []

        if agent:
            sql += " WHERE source_flavor = ? OR target_flavor = ?"
            params.extend([agent, agent])

        sql += " ORDER BY created_at DESC LIMIT ?"
        params.append(limit)

        try:
            conn = _connect(self._db_path)
            # Table may not exist yet — create it if missing
            conn.execute("""
                CREATE TABLE IF NOT EXISTS memory_influence_log (
                    id           INTEGER PRIMARY KEY AUTOINCREMENT,
                    source_flavor TEXT NOT NULL,
                    target_flavor TEXT NOT NULL,
                    source_iri    TEXT,
                    target_iri    TEXT,
                    link_type     TEXT DEFAULT 'prov:wasInfluencedBy',
                    created_at    TEXT NOT NULL
                )
            """)
            rows = conn.execute(sql, params).fetchall()
            conn.close()
            return [dict(r) for r in rows]
        except Exception as exc:
            print(f"  WARN AgentMemory.influence_graph: {exc}")
            return []

    # ─────────────────────────────────────────────────────────────────────
    # Consolidation strategies
    # ─────────────────────────────────────────────────────────────────────

    def _graph_size(self) -> int:
        """Return total active (non-invalidated) ObservationRecord count."""
        try:
            conn = _connect(self._db_path)
            row = conn.execute(
                "SELECT COUNT(*) as n FROM observation_record "
                "WHERE invalidated_by IS NULL OR invalidated_by = ''"
            ).fetchone()
            conn.close()
            return row["n"] if row else 0
        except Exception:
            return 0

    def _supersede_inferred(self, cutoff: str, dry_run: bool) -> int:
        """Strategy 1: MEASURED observation supersedes INFERRED for same entity.

        For each entity where both an INFERRED and a newer MEASURED record
        exist, marks the INFERRED record with ``prov:wasInvalidatedBy``
        pointing to the MEASURED record IRI.
        """
        try:
            conn = _connect(self._db_path)

            # Find INFERRED records that have a corresponding MEASURED record
            # on the same entity_iri with a later generation time
            candidates = conn.execute("""
                SELECT inferred.record_iri   AS inf_iri,
                       measured.record_iri   AS meas_iri
                FROM   observation_record AS inferred
                JOIN   observation_record AS measured
                       ON  inferred.entity_iri = measured.entity_iri
                WHERE  inferred.derivation_method  = 'INFERRED'
                  AND  measured.derivation_method  = 'MEASURED'
                  AND  measured.generated_at       > inferred.generated_at
                  AND  (inferred.invalidated_by IS NULL OR inferred.invalidated_by = '')
                  AND  inferred.generated_at       < ?
            """, (cutoff,)).fetchall()

            count = len(candidates)
            if not dry_run:
                now = _utcnow()
                for row in candidates:
                    conn.execute(
                        "UPDATE observation_record "
                        "SET invalidated_by = ?, updated_at = ? "
                        "WHERE record_iri = ?",
                        (row["meas_iri"], now, row["inf_iri"]),
                    )
                conn.commit()
            conn.close()
            return count

        except Exception as exc:
            print(f"  WARN AgentMemory._supersede_inferred: {exc}")
            return 0

    def _compress_old_observations(self, cutoff: str, dry_run: bool) -> int:
        """Strategy 2: Aggregate point observations older than cutoff.

        Groups MEASURED observations by entity_iri + record_type for the
        period older than ``cutoff``, inserts one summary record, and
        invalidates the constituent point records.
        """
        try:
            conn = _connect(self._db_path)

            # Find groups with more than one old point observation
            groups = conn.execute("""
                SELECT entity_iri,
                       record_type,
                       COUNT(*)           AS n,
                       MIN(generated_at)  AS earliest,
                       MAX(generated_at)  AS latest,
                       AVG(confidence_score) AS avg_conf
                FROM   observation_record
                WHERE  generated_at < ?
                  AND  derivation_method = 'MEASURED'
                  AND  (invalidated_by IS NULL OR invalidated_by = '')
                GROUP  BY entity_iri, record_type
                HAVING COUNT(*) > 1
            """, (cutoff,)).fetchall()

            compressed = 0
            now = _utcnow()

            for g in groups:
                # Create summary record
                summary_iri = f"{_BASE_IRI}memory/summary/{uuid.uuid4()}"
                if not dry_run:
                    conn.execute("""
                        INSERT OR IGNORE INTO observation_record (
                            record_iri, entity_iri, entity_type, record_type,
                            derivation_method, confidence_score,
                            value_text, generated_at, valid_from, created_at
                        ) VALUES (?, ?, ?, ?, 'SYNTHESIZED', ?, ?, ?, ?, ?)
                    """, (
                        summary_iri,
                        g["entity_iri"],
                        "ObservationSummary",
                        g["record_type"],
                        g["avg_conf"],
                        json.dumps({
                            "summary_type": "temporal_compression",
                            "point_count":  g["n"],
                            "earliest":     g["earliest"],
                            "latest":       g["latest"],
                        }),
                        now, g["earliest"], now,
                    ))

                    # Invalidate all constituent point records
                    conn.execute("""
                        UPDATE observation_record
                        SET    invalidated_by = ?, updated_at = ?
                        WHERE  entity_iri          = ?
                          AND  record_type          = ?
                          AND  generated_at         < ?
                          AND  derivation_method     = 'MEASURED'
                          AND  (invalidated_by IS NULL OR invalidated_by = '')
                    """, (summary_iri, now, g["entity_iri"], g["record_type"], cutoff))

                compressed += g["n"]

            if not dry_run:
                conn.commit()
            conn.close()
            return compressed

        except Exception as exc:
            print(f"  WARN AgentMemory._compress_old_observations: {exc}")
            return 0

    def _escalate_conflicts(self, dry_run: bool) -> int:
        """Strategy 3: Raise ConflictEvent for contradicting MEASURED observations.

        When two non-invalidated MEASURED observations exist for the same
        entity_iri with different value_text, creates a ConflictEvent
        ObservationRecord for human review.
        """
        try:
            conn = _connect(self._db_path)

            # Ensure updated_at column exists (added by consolidation daemon)
            try:
                conn.execute(
                    "ALTER TABLE observation_record ADD COLUMN updated_at TEXT"
                )
                conn.commit()
            except sqlite3.OperationalError:
                pass  # Column already exists

            conflicts = conn.execute("""
                SELECT a.record_iri   AS iri_a,
                       b.record_iri   AS iri_b,
                       a.entity_iri,
                       a.value_text   AS val_a,
                       b.value_text   AS val_b
                FROM   observation_record AS a
                JOIN   observation_record AS b
                       ON  a.entity_iri = b.entity_iri
                       AND a.record_iri < b.record_iri
                WHERE  a.derivation_method = 'MEASURED'
                  AND  b.derivation_method = 'MEASURED'
                  AND  (a.invalidated_by IS NULL OR a.invalidated_by = '')
                  AND  (b.invalidated_by IS NULL OR b.invalidated_by = '')
                  AND  a.value_text IS NOT NULL
                  AND  b.value_text IS NOT NULL
                  AND  a.value_text != b.value_text
            """).fetchall()

            count = len(conflicts)
            now = _utcnow()

            if not dry_run:
                for c in conflicts:
                    conflict_iri = f"{_BASE_IRI}memory/conflict/{uuid.uuid4()}"
                    conn.execute("""
                        INSERT OR IGNORE INTO observation_record (
                            record_iri, entity_iri, entity_type, record_type,
                            derivation_method, value_text, generated_at,
                            valid_from, created_at
                        ) VALUES (?, ?, 'ConflictEvent', 'CONFLICT', 'SYNTHESIZED', ?, ?, ?, ?)
                    """, (
                        conflict_iri,
                        c["entity_iri"],
                        json.dumps({
                            "conflict_type": "MEASURED_CONTRADICTION",
                            "record_a":      c["iri_a"],
                            "record_b":      c["iri_b"],
                            "value_a":       (c["val_a"] or "")[:200],
                            "value_b":       (c["val_b"] or "")[:200],
                        }),
                        now, now, now,
                    ))
                conn.commit()

            conn.close()
            return count

        except Exception as exc:
            print(f"  WARN AgentMemory._escalate_conflicts: {exc}")
            return 0

    # ─────────────────────────────────────────────────────────────────────
    # Row → JSON-LD serialisation
    # ─────────────────────────────────────────────────────────────────────

    def _row_to_jsonld(self, row: sqlite3.Row) -> Dict[str, Any]:
        """Convert an ObservationRecord DB row to a typed JSON-LD object."""
        d = dict(row)
        obj: Dict[str, Any] = {
            "@type":            "ObservationRecord",
            "@id":               d.get("record_iri", ""),
            "entity_iri":        d.get("entity_iri", ""),
            "entity_type":       d.get("entity_type", ""),
            "record_type":       d.get("record_type", ""),
            "derivation_method": d.get("derivation_method", ""),
            "confidence_score":  d.get("confidence_score"),
            "value_text":        d.get("value_text", ""),
            "source_ref":        d.get("source_ref", ""),
            "prov_agent_iri":    d.get("prov_agent_iri", ""),
            "generatedAt":       d.get("generated_at", ""),
            "valid_from":        d.get("valid_from", ""),
        }
        if d.get("invalidated_by"):
            obj["invalidatedBy"] = d["invalidated_by"]
        if d.get("kpi_type"):
            obj["kpi_type"] = d["kpi_type"]
        if d.get("value_numeric") is not None:
            obj["value_numeric"] = d["value_numeric"]
        if d.get("unit"):
            obj["unit"] = d["unit"]
        return obj
