"""
rbac_generator.py — Phase 2A / S8
────────────────────────────────────
Generates named-graph RBAC access control configurations from the
sensitivity tier annotations in ontology_metadata.

The generated configs partition the RDF store into four named graphs:
  Public        → any authenticated user
  Internal      → staff with data_reader role
  Confidential  → analysts and above
  Restricted    → data stewards and admins only

Three store targets are supported:
  stardog  → Stardog role-permission policy (stardog-rbac-policy.txt)
  fuseki   → Apache Jena Fuseki / Shiro config (shiro.ini + dataset config)
  neptune  → AWS Neptune IAM policy JSON (neptune-iam-policy.json)

Usage (via toolkit.py):
  python3 toolkit.py --phase security --store stardog
  python3 toolkit.py --phase security --store fuseki
  python3 toolkit.py --phase security --store neptune
  python3 toolkit.py --phase security --store all

Usage (direct):
  from rbac_generator import generate_rbac
  generate_rbac(intro, output_dir="output/security", store="all")
"""

from __future__ import annotations

import json
import os
from typing import Dict, List, Set

# ── Constants ─────────────────────────────────────────────────────────────

BASE_IRI = "https://ontology.example.com/enterprise/"

TIERS = ["Public", "Internal", "Confidential", "Restricted"]

# Named graph IRIs for each sensitivity tier
GRAPH_IRI = {t: f"{BASE_IRI}graph/{t}" for t in TIERS}

# Role definitions: name → maximum readable tiers (cumulative)
ROLES = {
    "public_user":    ["Public"],
    "data_reader":    ["Public", "Internal"],
    "data_analyst":   ["Public", "Internal", "Confidential"],
    "data_steward":   ["Public", "Internal", "Confidential", "Restricted"],
    "data_engineer":  ["Public", "Internal", "Confidential"],
    "ontology_admin": ["Public", "Internal", "Confidential", "Restricted"],
}

# Roles that can write as well as read
WRITE_ROLES = {"data_steward", "ontology_admin"}


# ── Tier assignment ───────────────────────────────────────────────────────

def _collect_tier_map(tables) -> Dict[str, str]:
    """Return {class_name: sensitivity_tier} from TableModel list."""
    return {t.class_name: t.sensitivity_tier for t in tables}


# ── Stardog RBAC policy ───────────────────────────────────────────────────

def _stardog_policy(tier_map: Dict[str, str]) -> str:
    tier_classes: Dict[str, List[str]] = {t: [] for t in TIERS}
    for cls, tier in tier_map.items():
        if tier in tier_classes:
            tier_classes[tier].append(cls)

    lines = [
        "# ──────────────────────────────────────────────────────────────────",
        "# Stardog Named-Graph RBAC Policy",
        "# Generated by Ontology Engineering Toolkit — rbac_generator.py",
        "# Apply with: stardog-admin role add / permission add",
        "# ──────────────────────────────────────────────────────────────────",
        "",
        "# Named graph assignments by sensitivity tier",
    ]
    for tier, classes in tier_classes.items():
        lines.append(f"# {GRAPH_IRI[tier]}")
        if classes:
            lines.append(f"#   Classes: {', '.join(sorted(classes))}")
    lines.append("")

    for role, readable_tiers in ROLES.items():
        lines.append(f"# ── Role: {role} ──────────────────────────────────")
        for tier in readable_tiers:
            action = "read,write" if role in WRITE_ROLES else "read"
            lines.append(
                f"GRANT {action.upper()} ON NAMED GRAPH <{GRAPH_IRI[tier]}> TO {role};"
            )
        # Explicit DENY for tiers above ceiling
        denied = [t for t in TIERS if t not in readable_tiers]
        for tier in denied:
            lines.append(
                f"DENY  READ  ON NAMED GRAPH <{GRAPH_IRI[tier]}> TO {role};"
            )
        lines.append("")

    lines += [
        "# ── Role definitions (run once) ──────────────────────────────────",
    ]
    for role in ROLES:
        lines.append(f"stardog-admin role add {role}")
    lines.append("")
    lines += [
        "# ── Sample user assignments ──────────────────────────────────────",
        "# stardog-admin user add alice --superuser false",
        "# stardog-admin role assign alice data_analyst",
        "# stardog-admin role assign bob  data_steward",
    ]
    return "\n".join(lines) + "\n"


# ── Apache Fuseki / Shiro ─────────────────────────────────────────────────

def _fuseki_shiro(tier_map: Dict[str, str]) -> str:
    lines = [
        "# ──────────────────────────────────────────────────────────────────",
        "# Apache Jena Fuseki — Shiro security.ini",
        "# Generated by Ontology Engineering Toolkit — rbac_generator.py",
        "# Place this file at FUSEKI_HOME/shiro.ini",
        "# ──────────────────────────────────────────────────────────────────",
        "",
        "[main]",
        "# Uncomment and configure a real realm for production:",
        "# iniRealm = org.apache.shiro.realm.text.IniRealm",
        "# $iniRealm.userDefinitions = $users",
        "# $iniRealm.roleDefinitions = $roles",
        "",
        "[users]",
        "# username = password, role1, role2",
        "# IMPORTANT: Replace passwords before deployment",
    ]
    sample_users = {
        "viewer":    ("change-me-viewer",    "public_user"),
        "analyst":   ("change-me-analyst",   "data_analyst"),
        "steward":   ("change-me-steward",   "data_steward"),
        "admin":     ("change-me-admin",     "ontology_admin"),
    }
    for user, (pwd, role) in sample_users.items():
        lines.append(f"{user} = {pwd}, {role}")

    lines += [
        "",
        "[roles]",
        "# role = permission1, permission2",
        "# Permissions use Fuseki path pattern: /dataset/graph/TIER:read",
    ]
    for role, readable_tiers in ROLES.items():
        perms = []
        for tier in readable_tiers:
            perms.append(f"ontology:graph:{tier}:read")
        if role in WRITE_ROLES:
            for tier in readable_tiers:
                perms.append(f"ontology:graph:{tier}:write")
        lines.append(f"{role} = {', '.join(perms)}")

    lines += [
        "",
        "[urls]",
        "# URL pattern → required roles",
        "/$/ping = anon",
        "/$/server = roles[ontology_admin]",
        "/ontology/query = authcBasic, roles[public_user, data_reader, data_analyst, data_steward, ontology_admin]",
        "/ontology/update = authcBasic, roles[data_steward, ontology_admin]",
        "/ontology/upload = authcBasic, roles[ontology_admin]",
        "/** = authcBasic",
    ]
    return "\n".join(lines) + "\n"


def _fuseki_dataset_config(tier_map: Dict[str, str]) -> str:
    """Generate an Apache Jena / RDF4J dataset config with named graph assignments."""
    tier_classes: Dict[str, List[str]] = {t: [] for t in TIERS}
    for cls, tier in tier_map.items():
        if tier in tier_classes:
            tier_classes[tier].append(cls)

    lines = [
        "@prefix :     <#> .",
        "@prefix fuseki: <http://jena.apache.org/fuseki#> .",
        "@prefix rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .",
        "@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .",
        "@prefix ja:   <http://jena.hpl.hp.com/2005/11/Assembler#> .",
        "",
        "# ── Fuseki Dataset Configuration ─────────────────────────────────",
        "# Named graphs mapped to sensitivity tiers",
        "",
        ":ontologyService a fuseki:Service ;",
        '    fuseki:name "ontology" ;',
        "    fuseki:endpoint [ fuseki:operation fuseki:query  ; fuseki:name \"query\" ] ;",
        "    fuseki:endpoint [ fuseki:operation fuseki:update ; fuseki:name \"update\" ] ;",
        "    fuseki:dataset :tieredDataset .",
        "",
        ":tieredDataset a ja:RDFDataset ;",
    ]
    for tier in TIERS:
        lines.append(f"    ja:namedGraph [ ja:graphName <{GRAPH_IRI[tier]}> ; ja:graph :graph{tier} ] ;")
    lines.append("    .")
    lines.append("")
    for tier in TIERS:
        classes = tier_classes.get(tier, [])
        lines += [
            f":graph{tier} a ja:MemoryModel ;",
            f"    # Sensitivity tier: {tier}",
            f"    # Classes: {', '.join(sorted(classes)) if classes else '(none)'}",
            "    .",
            "",
        ]
    return "\n".join(lines) + "\n"


# ── Amazon Neptune IAM policy ─────────────────────────────────────────────

def _neptune_iam_policy(tier_map: Dict[str, str], account_id: str = "ACCOUNT_ID",
                         region: str = "REGION", cluster_id: str = "CLUSTER_ID") -> str:
    statements = []

    for role, readable_tiers in ROLES.items():
        graph_arns = [
            f"arn:aws:neptune-db:{region}:{account_id}:cluster:{cluster_id}/graph/{tier.lower()}"
            for tier in readable_tiers
        ]
        actions = ["neptune-db:ReadDataViaQuery"]
        if role in WRITE_ROLES:
            actions += ["neptune-db:WriteDataViaQuery", "neptune-db:DeleteDataViaQuery"]

        statements.append({
            "Sid": f"Allow{role.replace('_','').title()}",
            "Effect": "Allow",
            "Principal": {
                "AWS": f"arn:aws:iam::{account_id}:role/{role.replace('_','-')}"
            },
            "Action": actions,
            "Resource": graph_arns,
        })

    # Explicit deny for roles that should NOT access Restricted
    restricted_roles = [r for r, tiers in ROLES.items() if "Restricted" not in tiers]
    if restricted_roles:
        statements.append({
            "Sid": "DenyRestrictedToNonStewards",
            "Effect": "Deny",
            "Principal": {
                "AWS": [
                    f"arn:aws:iam::{account_id}:role/{r.replace('_','-')}"
                    for r in restricted_roles
                ]
            },
            "Action": ["neptune-db:ReadDataViaQuery", "neptune-db:WriteDataViaQuery"],
            "Resource": [
                f"arn:aws:neptune-db:{region}:{account_id}:cluster:{cluster_id}/graph/restricted"
            ],
        })

    policy = {
        "Version": "2012-10-17",
        "Comment": "Generated by Ontology Engineering Toolkit — rbac_generator.py",
        "Statement": statements,
    }
    return json.dumps(policy, indent=2) + "\n"


# ── Markdown summary ──────────────────────────────────────────────────────

def _rbac_summary(tier_map: Dict[str, str]) -> str:
    tier_counts: Dict[str, int] = {t: 0 for t in TIERS}
    for tier in tier_map.values():
        if tier in tier_counts:
            tier_counts[tier] += 1

    lines = [
        "# Named-Graph RBAC Summary",
        "",
        "Generated by Ontology Engineering Toolkit — Phase 2A",
        "",
        "## Named graph assignments",
        "",
        "| Named graph IRI | Sensitivity tier | Class count |",
        "|---|---|---|",
    ]
    for tier in TIERS:
        lines.append(f"| `{GRAPH_IRI[tier]}` | {tier} | {tier_counts[tier]} |")

    lines += [
        "",
        "## Role access matrix",
        "",
        "| Role | Public | Internal | Confidential | Restricted | Write |",
        "|---|:---:|:---:|:---:|:---:|:---:|",
    ]
    for role, readable_tiers in ROLES.items():
        cells = ["✓" if t in readable_tiers else "—" for t in TIERS]
        write_cell = "✓" if role in WRITE_ROLES else "—"
        lines.append(f"| `{role}` | {' | '.join(cells)} | {write_cell} |")

    lines += [
        "",
        "## Class–graph mapping",
        "",
        "| OWL Class | Named graph | Sensitivity |",
        "|---|---|---|",
    ]
    for cls in sorted(tier_map):
        tier = tier_map[cls]
        lines.append(f"| `{cls}` | `{GRAPH_IRI.get(tier, '(unknown)')}` | {tier} |")

    lines += [
        "",
        "## Generated configs",
        "",
        "| File | Target | Notes |",
        "|---|---|---|",
        "| `stardog-rbac-policy.txt` | Stardog | GRANT/DENY statements, run with stardog-admin |",
        "| `shiro.ini` | Apache Fuseki | Drop in FUSEKI_HOME — replace passwords before deploying |",
        "| `fuseki-dataset.ttl` | Apache Fuseki | Named-graph dataset assembler config |",
        "| `neptune-iam-policy.json` | Amazon Neptune | Replace ACCOUNT_ID, REGION, CLUSTER_ID |",
    ]
    return "\n".join(lines) + "\n"


# ── Public entry point ────────────────────────────────────────────────────

def generate_rbac(intro, output_dir: str, store: str = "all"):
    """
    Generate RBAC configs for the given store type.

    Args:
        intro:      DBIntrospector instance (already opened)
        output_dir: Directory to write config files into
        store:      'stardog' | 'fuseki' | 'neptune' | 'all'
    """
    os.makedirs(output_dir, exist_ok=True)

    tables    = intro.introspect_all()
    tier_map  = _collect_tier_map(tables)

    unique_tiers = set(tier_map.values())
    print(f"\n  Generating RBAC configs  [store: {store}]")
    print(f"  {len(tier_map)} classes across {len(unique_tiers)} sensitivity tiers: "
          f"{', '.join(sorted(unique_tiers))}")

    files_written = []

    if store in ("stardog", "all"):
        path = os.path.join(output_dir, "stardog-rbac-policy.txt")
        with open(path, "w") as f:
            f.write(_stardog_policy(tier_map))
        print(f"  ✓ Stardog RBAC policy   → {path}")
        files_written.append(path)

    if store in ("fuseki", "all"):
        path = os.path.join(output_dir, "shiro.ini")
        with open(path, "w") as f:
            f.write(_fuseki_shiro(tier_map))
        print(f"  ✓ Fuseki shiro.ini      → {path}")
        files_written.append(path)

        path = os.path.join(output_dir, "fuseki-dataset.ttl")
        with open(path, "w") as f:
            f.write(_fuseki_dataset_config(tier_map))
        print(f"  ✓ Fuseki dataset config → {path}")
        files_written.append(path)

    if store in ("neptune", "all"):
        path = os.path.join(output_dir, "neptune-iam-policy.json")
        with open(path, "w") as f:
            f.write(_neptune_iam_policy(tier_map))
        print(f"  ✓ Neptune IAM policy    → {path}")
        files_written.append(path)

    # Always write summary
    path = os.path.join(output_dir, "rbac-summary.md")
    with open(path, "w") as f:
        f.write(_rbac_summary(tier_map))
    print(f"  ✓ RBAC summary          → {path}")
    files_written.append(path)

    print(f"  RBAC: {len(files_written)} config files written to {output_dir}")
    return files_written
